name: Terraform Apply
on: workflow_dispatch #trigger manualmente
env:
  AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
  AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
  AWS_SESSION_TOKEN: ${{secrets.AWS_SECRET_SESSION_TOKEN}}
  ARM_CLIENT_ID: ${{secrets.ARM_CLIENT_ID}}
  ARM_TENANT_ID: ${{secrets.ARM_TENANT_ID}}
  ARM_SUBSCRIPTION_ID: ${{secrets.ARM_SUBSCRIPTION_ID}}
  ARM_CLIENT_SECRET: ${{secrets.ARM_CLIENT_SECRET}}
  TF_VAR_aws_pub_key: ${{secrets.AWS_PUBLIC_KEY}}
  TF_VAR_azure_pub_key: ${{secrets.AZURE_PUBLIC_KEY}}
jobs:
  terraform:
    name: terraform
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: checkout #faz o download dos arquivos do respositorio para pipeline
        uses: actions/checkout@v2
      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve
